version: '2'
services:
  jenkins-data:
    image: busybox
    volumes:
    - /data/docker_data/jenkins:/var/jenkins_home
    labels:
      io.rancher.container.start_once: 'true'
  jenkins:
    image: jenkins-erlang
    stdin_open: true
    network_mode: bridge
    tty: true
    volumes_from:
    - jenkins-data
    ports:
    - 9009:3306/tcp
    labels:
      io.rancher.sidekicks: jenkins-data
